//
// This file is generated by parsec-rdl-gen (development version)
// WILL NOT be auto-generated if file has already existed.
//
package com.yamlin;

import com.yamlin.BO.TraderBO;
import com.yamlin.BO.TransactionBO;
import com.yamlin.parsec_generated.*;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * WebappHandlerImpl is interface implementation that implement WebappHandler interface.
 */
public class WebappHandlerImpl implements WebappHandler {
    @Inject private TransactionBO transactionBO;
    @Inject private TraderBO traderBO;


    @Override
    public TraderList getTraders(ResourceContext context, String q, String sinceId, Integer count, String orderBy) {
        return traderBO.getTrader(q, sinceId, count, orderBy);
    }

    @Override
    public TransactionList getTransactions(ResourceContext context, String q, String sinceId, Integer count, String orderBy) {
        return transactionBO.getTransactions(q);
    }

    @Override
    public TransactionSummary getTransactionSummary(ResourceContext context, String q, String op) {
        return transactionBO.getTransactions(q, op);
    }

    @Override
    public ResourceContext newResourceContext(HttpServletRequest request, HttpServletResponse response) {
        return new DefaultResourceContext(request, response);
    }
}
